Repository ICE-LIFE/ICE-LIFE-Backend, pull requests merged in 2022-08, with the labels that each got.

#24 [Refactor/#13] ChatController 리팩터링
  src/main/java/life/inha/icemarket/controller/ChatController.java
  src/main/java/life/inha/icemarket/exception/BadRequestException.java
  src/main/java/life/inha/icemarket/exception/ConflictException.java
  src/main/java/life/inha/icemarket/exception/ForbiddenException.java
  src/main/java/life/inha/icemarket/exception/NotFoundException.java
  src/main/java/life/inha/icemarket/exception/RoomNotFoundException.java
  src/main/java/life/inha/icemarket/exception/UserNotFoundException.java
  src/main/java/life/inha/icemarket/service/ChatService.java
Labels: refactoring

#27 [Config/#25] Update java and gradle version
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#28 [Feature/#6] 로그인, 비밀번호 초기화, jwt 인증 구현
  .DS_Store
  .env.example
  README.md
  build.gradle
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/life/.DS_Store
  src/main/java/life/inha/.DS_Store
  src/main/java/life/inha/icemarket/.DS_Store
  src/main/java/life/inha/icemarket/config/JwtAuthenticationEntryPoint.java
  src/main/java/life/inha/icemarket/config/JwtAuthenticationFilter.java
  src/main/java/life/inha/icemarket/config/JwtTokenProvider.java
  src/main/java/life/inha/icemarket/config/SecurityConfig.java
  src/main/java/life/inha/icemarket/config/Token.java
  src/main/java/life/inha/icemarket/config/UserAuthentication.java
  src/main/java/life/inha/icemarket/controller/LoginApiController.java
  src/main/java/life/inha/icemarket/controller/UserApiController.java
  src/main/java/life/inha/icemarket/domain/User.java
  src/main/java/life/inha/icemarket/domain/UserRole.java
  src/main/java/life/inha/icemarket/respository/UserRepository.java
  src/main/java/life/inha/icemarket/service/CustomUserDetails.java
  src/main/java/life/inha/icemarket/service/UserSecurityService.java
  src/main/java/life/inha/icemarket/service/UserService.java
  src/main/resources/static/bootstrap.min.css
  src/main/resources/static/bootstrap.min.js
  src/main/resources/templates/find_pw.html
  src/main/resources/templates/resetpw.html
Labels: enhancement

#30 [Refactor/#29] 코드 구조 리펙토링 및 Api문서 작성
  src/main/java/life/inha/icemarket/controller/FindPasswordController.java
  src/main/java/life/inha/icemarket/controller/LoginController.java
  src/main/java/life/inha/icemarket/controller/SignupController.java
  src/main/java/life/inha/icemarket/domain/User.java
Labels: documentation, refactoring

#31 [Feature/#17] 댓글 CRD 구현
  src/main/java/life/inha/icemarket/controller/CommentController.java
  src/main/java/life/inha/icemarket/domain/Comment.java
  src/main/java/life/inha/icemarket/dto/GetCommentRes.java
  src/main/java/life/inha/icemarket/dto/PostCommentReq.java
  src/main/java/life/inha/icemarket/dto/PostCommentRes.java
  src/main/java/life/inha/icemarket/respository/CommentRepository.java
  src/main/java/life/inha/icemarket/service/CommentService.java
  src/test/java/life/inha/icemarket/controller/CommentControllerTest.java
Labels: enhancement

#33 [Refactor/#32] JWT 발급 코드 최적화
  build.gradle
  src/main/java/life/inha/icemarket/config/JwtAuthenticationFilter.java
  src/main/java/life/inha/icemarket/config/JwtDecodeFilter.java
  src/main/java/life/inha/icemarket/config/JwtLoginFilter.java
  src/main/java/life/inha/icemarket/config/JwtTokenProvider.java
  src/main/java/life/inha/icemarket/config/SecurityConfig.java
  src/main/java/life/inha/icemarket/config/UserAuthentication.java
  src/main/java/life/inha/icemarket/controller/LoginController.java
  src/main/java/life/inha/icemarket/domain/User.java
  src/main/java/life/inha/icemarket/service/UserSecurityService.java
Labels: refactoring

#37 JWT 인증 기능 추가
  src/main/java/life/inha/icemarket/config/JwtDecodeFilter.java
  src/main/java/life/inha/icemarket/config/JwtLoginFilter.java
  src/main/java/life/inha/icemarket/config/SecurityConfig.java
  src/main/java/life/inha/icemarket/controller/FindPasswordController.java
  src/main/java/life/inha/icemarket/controller/SignupController.java
  src/main/java/life/inha/icemarket/controller/WhoAmIController.java
  src/main/java/life/inha/icemarket/domain/User.java
  src/main/java/life/inha/icemarket/domain/UserRole.java
  src/main/java/life/inha/icemarket/service/UserCreateService.java
  src/main/java/life/inha/icemarket/service/UserSecurityService.java
Labels: enhancement

#38 [Feature/#26] NGINX와 HTTPS 적용
  .gitignore
  docker-compose.yml
  nginx/default.conf
Labels: enhancement

#41 [Feature/#40] WS 채팅에 JWT 사용자 인증 적용
  src/main/java/life/inha/icemarket/config/SecurityConfig.java
  src/main/java/life/inha/icemarket/config/WebSocketConfig.java
  src/main/java/life/inha/icemarket/controller/ChatController.java
  src/main/java/life/inha/icemarket/service/ChatService.java
Labels: enhancement

#43 [hotfix/#42] UserRole : GUEST 권한 및 /signup 페이지 권한 재설정
  src/main/java/life/inha/icemarket/config/SecurityConfig.java
  src/main/java/life/inha/icemarket/domain/User.java
  src/main/java/life/inha/icemarket/domain/UserRole.java
  src/main/java/life/inha/icemarket/service/UserSecurityService.java
Labels: hotfix

#48 [Refactor/#46] 복지물품 게시판 컨트롤러 RESTful하게 리팩토링
  build.gradle
  src/main/java/life/inha/icemarket/controller/ItemController.java
  src/main/java/life/inha/icemarket/controller/ItemHistoryController.java
Labels: refactoring

#49 [Refactor/#47] 사용자 컨트롤러 테스트 코드 작성
  src/main/java/life/inha/icemarket/config/JwtDecodeFilter.java
  src/main/java/life/inha/icemarket/config/SecurityConfig.java
  src/main/java/life/inha/icemarket/controller/FindPasswordController.java
  src/main/java/life/inha/icemarket/controller/SignupController.java
  src/main/java/life/inha/icemarket/service/UserSecurityService.java
  src/main/resources/templates/find_pw.html
  src/main/resources/templates/resetpw.html
  src/test/java/life/inha/icemarket/controller/UserControllerTest.java
Labels: enhancement

#51 [Config/#51] API 문서 항상 접근 가능하게 허용
  src/main/java/life/inha/icemarket/config/SecurityConfig.java
Labels: hotfix

#52 [Config/#51] .DS_Store 파일 삭제
  .DS_Store
  .gitignore
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/life/.DS_Store
  src/main/java/life/inha/.DS_Store
  src/main/java/life/inha/icemarket/.DS_Store
Labels: hotfix

#57 [feature/#56] 이메일 인증기능 추가 (인증번호 고정)
  build.gradle
  db/init.sql
  src/main/java/life/inha/icemarket/config/SecurityConfig.java
  src/main/java/life/inha/icemarket/controller/EmailController.java
  src/main/java/life/inha/icemarket/controller/FindPasswordController.java
  src/main/java/life/inha/icemarket/controller/SignupController.java
  src/main/java/life/inha/icemarket/domain/User.java
  src/main/java/life/inha/icemarket/dto/EmailDto.java
  src/main/java/life/inha/icemarket/dto/UserCreateDto.java
  src/main/java/life/inha/icemarket/service/EmailService.java
  src/main/java/life/inha/icemarket/service/EmailServiceImpl.java
  src/main/java/life/inha/icemarket/service/UserCreateService.java
  src/main/java/life/inha/icemarket/service/UserRoleService.java
  src/main/java/life/inha/icemarket/service/UserSecurityService.java
  src/main/resources/application.properties
  src/main/resources/templates/ConfirmEmail.html
  src/main/resources/templates/resetpw.html
  src/main/resources/templates/signup.html
Labels: enhancement

#59 [hotfix/#58] merge
  build.gradle
  src/main/java/life/inha/icemarket/config/SecurityConfig.java
Labels: bug, hotfix

#68 [Config/#67] 로그인 api 문서 등록
  src/main/java/life/inha/icemarket/controller/AuthApi.java
  src/main/java/life/inha/icemarket/controller/EmailController.java
  src/main/java/life/inha/icemarket/controller/SignupController.java
Labels: documentation

#71 [Feature/#56] 이메일 인증방식 변경
  db/init.sql
  src/main/java/life/inha/icemarket/controller/EmailController.java
  src/main/java/life/inha/icemarket/controller/SignupController.java
  src/main/java/life/inha/icemarket/domain/User.java
  src/main/java/life/inha/icemarket/service/EmailService.java
  src/main/java/life/inha/icemarket/service/EmailServiceImpl.java
  src/main/java/life/inha/icemarket/service/UserCreateService.java
  src/main/java/life/inha/icemarket/service/UserSecurityService.java
  src/test/java/life/inha/icemarket/controller/UserControllerTest.java
Labels: enhancement

#72 [Feature/#10] AdminService 내용추가
  src/main/java/life/inha/icemarket/controller/AdminController.java
  src/main/java/life/inha/icemarket/domain/User.java
  src/main/java/life/inha/icemarket/respository/CommentRepository.java
  src/main/java/life/inha/icemarket/respository/PostRepository.java
  src/main/java/life/inha/icemarket/service/AdminService.java
Labels: enhancement

#75 [Refactor/#73] API Document 업데이트
  src/main/java/life/inha/icemarket/config/swagger/LoginAPIDocument.java
  src/main/java/life/inha/icemarket/controller/EmailController.java
  src/main/java/life/inha/icemarket/controller/FindPasswordController.java
  src/main/java/life/inha/icemarket/controller/SignupController.java
Labels: documentation

#77 [Refactor/#47] 사용자 컨트롤러 테스트 코드 작성
  src/main/java/life/inha/icemarket/config/SecurityConfig.java
  src/main/java/life/inha/icemarket/controller/EmailController.java
  src/main/java/life/inha/icemarket/controller/SignupController.java
  src/main/java/life/inha/icemarket/dto/EmailDto.java
  src/main/java/life/inha/icemarket/service/UserSecurityService.java
  src/test/java/life/inha/icemarket/controller/UserControllerTest.java
Labels: enhancement

#79 [Config/#79] NGINX에 웹 소켓 설정 추가
  nginx/default.conf
Labels: bug

#78 [Feature/#44] 웹소켓 채팅 컨트롤러 테스트 코드 작성
  src/test/java/life/inha/icemarket/controller/ChatControllerTest.java
Labels: enhancement

#84 [Refactor/#70] Comment 코드 리팩토링
  src/main/java/life/inha/icemarket/controller/CommentController.java
  src/main/java/life/inha/icemarket/domain/Comment.java
  src/main/java/life/inha/icemarket/dto/CommentResDto.java
  src/main/java/life/inha/icemarket/dto/CommentSaveReqDto.java
  src/main/java/life/inha/icemarket/dto/CommentSaveResDto.java
  src/main/java/life/inha/icemarket/respository/CommentRepository.java
  src/main/java/life/inha/icemarket/respository/PostRepository.java
  src/main/java/life/inha/icemarket/service/CommentService.java
  src/test/java/life/inha/icemarket/controller/CommentControllerTest.java
Labels: refactoring

#83 [Feature/#80] 인하대 이메일 도메인만 회원가입 허가 구현
  src/main/java/life/inha/icemarket/controller/EmailController.java
  src/main/java/life/inha/icemarket/controller/FindPasswordController.java
  src/main/java/life/inha/icemarket/controller/SignupController.java
  src/main/java/life/inha/icemarket/dto/UserCreateDto.java
  src/test/java/life/inha/icemarket/controller/UserControllerTest.java
Labels: enhancement

#87 [Config/#87] CORS 설정
  src/main/java/life/inha/icemarket/config/SecurityConfig.java
Labels: enhancement

#88 [Feature/#85] Comment 테스트 코드 작성
  src/main/java/life/inha/icemarket/domain/Post.java
  src/test/java/life/inha/icemarket/controller/CommentControllerTest.java
Labels: enhancement

#89 [Hotfix/#81] DB users테이블의 role컬럼 String화
  src/main/java/life/inha/icemarket/domain/User.java
Labels: hotfix

#90 [Refactor/#70] DB에 comment 테이블 추가, pk 매핑 방법 변경
  db/init.sql
  src/main/java/life/inha/icemarket/domain/Comment.java
Labels: refactoring, hotfix

#92 [Feature/#91] 이메일 인증을 통한 비밀번호 초기화 구현 및 테스트 코드 작성
  src/main/java/life/inha/icemarket/config/SecurityConfig.java
  src/main/java/life/inha/icemarket/controller/EmailController.java
  src/main/java/life/inha/icemarket/controller/FindPasswordController.java
  src/main/java/life/inha/icemarket/service/EmailService.java
  src/main/java/life/inha/icemarket/service/EmailServiceImpl.java
  src/main/resources/templates/find_pw.html
  src/main/resources/templates/findpw_code.html
  src/test/java/life/inha/icemarket/controller/UserControllerTest.java
Labels: enhancement

#93 프론트엔드 작업을 위한 반환값(html -> string) 수정
  src/main/java/life/inha/icemarket/controller/FindPasswordController.java
  src/main/java/life/inha/icemarket/controller/SignupController.java
Labels: hotfix

#62 Feature/#9 게시글 CRUD 구현
  src/main/java/life/inha/icemarket/controller/PostController.java
  src/main/java/life/inha/icemarket/domain/BaseTimeEntity.java
  src/main/java/life/inha/icemarket/domain/Category.java
  src/main/java/life/inha/icemarket/domain/Post.java
  src/main/java/life/inha/icemarket/domain/User.java
  src/main/java/life/inha/icemarket/dto/PostDto.java
  src/main/java/life/inha/icemarket/dto/PostSaveDto.java
  src/main/java/life/inha/icemarket/respository/CategoryRepository.java
  src/main/java/life/inha/icemarket/respository/PostRepository.java
  src/main/java/life/inha/icemarket/service/PostService.java
Labels: enhancement

#94 [Hotfix] 버그 수정 및 코드 정렬
  src/main/java/life/inha/icemarket/config/JwtDecodeFilter.java
  src/main/java/life/inha/icemarket/config/JwtLoginFilter.java
  src/main/java/life/inha/icemarket/config/QuerydslConfig.java
  src/main/java/life/inha/icemarket/config/swagger/LoginAPIDocument.java
  src/main/java/life/inha/icemarket/config/swagger/SwaggerConfig.java
  src/main/java/life/inha/icemarket/controller/AdminController.java
  src/main/java/life/inha/icemarket/controller/CommentController.java
  src/main/java/life/inha/icemarket/controller/EmailController.java
  src/main/java/life/inha/icemarket/controller/FindPasswordController.java
  src/main/java/life/inha/icemarket/controller/ItemController.java
  src/main/java/life/inha/icemarket/controller/ItemHistoryController.java
  src/main/java/life/inha/icemarket/controller/MyPageController.java
  src/main/java/life/inha/icemarket/controller/PostController.java
  src/main/java/life/inha/icemarket/controller/SignupController.java
  src/main/java/life/inha/icemarket/controller/WhoAmIController.java
  src/main/java/life/inha/icemarket/domain/BaseTimeEntity.java
  src/main/java/life/inha/icemarket/domain/Category.java
  src/main/java/life/inha/icemarket/domain/Comment.java
  src/main/java/life/inha/icemarket/domain/User.java
  src/main/java/life/inha/icemarket/domain/UserRole.java
  src/main/java/life/inha/icemarket/dto/CommentResDto.java
  src/main/java/life/inha/icemarket/dto/CommentSaveReqDto.java
  src/main/java/life/inha/icemarket/dto/CommentSaveResDto.java
  src/main/java/life/inha/icemarket/dto/EmailDto.java
  src/main/java/life/inha/icemarket/dto/PostDto.java
  src/main/java/life/inha/icemarket/dto/PostSaveDto.java
  src/main/java/life/inha/icemarket/dto/UserCreateDto.java
  src/main/java/life/inha/icemarket/dto/UserListDto.java
  src/main/java/life/inha/icemarket/respository/CommentRepository.java
  src/main/java/life/inha/icemarket/respository/UserRepository.java
  src/main/java/life/inha/icemarket/respository/UserRepositoryImpl.java
  src/main/java/life/inha/icemarket/service/AdminService.java
  src/main/java/life/inha/icemarket/service/CommentService.java
  src/main/java/life/inha/icemarket/service/CustomUserDetails.java
  src/main/java/life/inha/icemarket/service/EmailService.java
  src/main/java/life/inha/icemarket/service/EmailServiceImpl.java
  src/main/java/life/inha/icemarket/service/PostService.java
  src/main/java/life/inha/icemarket/service/UserCreateService.java
  src/main/java/life/inha/icemarket/service/UserRoleService.java
  src/main/java/life/inha/icemarket/service/UserSecurityService.java
  src/main/resources/application.properties
  src/main/resources/templates/ConfirmEmail.html
  src/main/resources/templates/find_pw.html
  src/main/resources/templates/findpw_code.html
  src/main/resources/templates/resetpw.html
  src/main/resources/templates/signup.html
  src/test/java/life/inha/icemarket/controller/AdminControllerTest.java
  src/test/java/life/inha/icemarket/controller/CommentControllerTest.java
  src/test/java/life/inha/icemarket/controller/UserControllerTest.java
Labels: bug, enhancement

#95 [Hotfix] 변수명, 데이터 타입 변경
  src/main/java/life/inha/icemarket/controller/CommentController.java
  src/main/java/life/inha/icemarket/domain/Category.java
  src/main/java/life/inha/icemarket/domain/Comment.java
  src/main/java/life/inha/icemarket/domain/Post.java
  src/main/java/life/inha/icemarket/respository/PostRepository.java
  src/main/java/life/inha/icemarket/service/CommentService.java
Labels: hotfix

#96 [Hotfix/#96] Post ID 타입 오류 및 컨트롤러 경로 수정
  src/main/java/life/inha/icemarket/controller/PostController.java
  src/main/java/life/inha/icemarket/domain/BaseTimeEntity.java
  src/main/java/life/inha/icemarket/dto/PostDto.java
  src/main/java/life/inha/icemarket/service/PostService.java
Labels: bug

#97 [Feature/#97] 새로 참가한 방 정보 출력 및 출력 형식 JSON화
  API.md
  src/main/java/life/inha/icemarket/service/ChatService.java
Labels: documentation, enhancement

#98 [Hotfix] id 타입 변경
  src/main/java/life/inha/icemarket/respository/CategoryRepository.java
Labels: hotfix

#99 [Feature] Post DTO에서 작성자 학번을 출력하게 수정
  src/main/java/life/inha/icemarket/controller/PostController.java
  src/main/java/life/inha/icemarket/dto/CommentResDto.java
  src/main/java/life/inha/icemarket/dto/PostDto.java
  src/main/java/life/inha/icemarket/service/PostService.java
Labels: enhancement

#100 [Hotfix] 작성자 별명 출력 설정 및 채팅방 초대 신호 전달
  src/main/java/life/inha/icemarket/dto/CommentResDto.java
  src/main/java/life/inha/icemarket/dto/PostDto.java
  src/main/java/life/inha/icemarket/service/ChatService.java
Labels: hotfix
