Repository ICE-LIFE/ICE-LIFE-Backend, pull requests merged in 2022-07, with the labels that each got.

#2 Initial commit
  .env.example
  .gitignore
  README.md
  build.gradle
  db/init.sql
  docker-compose.db.yml
  docker-compose.yml
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle
  src/main/java/life/inha/icemarket/DockerSecretPostProcessor.java
  src/main/java/life/inha/icemarket/IceMarketApplication.java
  src/main/java/life/inha/icemarket/User.java
  src/main/java/life/inha/icemarket/UserRepository.java
  src/main/resources/META-INF/spring.factories
  src/main/resources/application.properties
  src/test/java/life/inha/icemarket/IceMarketApplicationTests.java
Labels: enhancement

#3 Remove duplicate file and fix space style
  build.gradle
  src/main/java/com/ice/web/WebApplication.java
  src/test/java/com/ice/web/WebApplicationTests.java
  src/test/java/life/inha/icemarket/IceMarketApplicationTests.java
Labels: enhancement

#8 [Feature/#7] 마이페이지 기능 구현
  build.gradle
  settings.gradle
  src/main/java/life/inha/icemarket/IceMarketApplication.java
  src/main/java/life/inha/icemarket/controller/auth/MyPageController.java
  src/main/java/life/inha/icemarket/controller/auth/dummy.txt
  src/main/java/life/inha/icemarket/controller/core/dummy.txt
  src/main/java/life/inha/icemarket/domain/auth/User.java
  src/main/java/life/inha/icemarket/domain/core/Post.java
  src/main/java/life/inha/icemarket/domain/core/dummy.txt
  src/main/java/life/inha/icemarket/dto/MyPageDto.java
  src/main/java/life/inha/icemarket/service/auth/MyPageService.java
  src/main/java/life/inha/icemarket/service/auth/dummy.txt
  src/main/resources/application.properties
  src/test/java/life/inha/icemarket/controller/auth/MyPageControllerTest.java
Labels: enhancement

#15 [Refactor/#12] Java Primitive 자료형 Wrapper 클래스로 통일하기 + auth/user 구조 리팩터링
  db/init.sql
  src/main/java/life/inha/icemarket/IceMarketApplication.java
  src/main/java/life/inha/icemarket/controller/ChatController.java
  src/main/java/life/inha/icemarket/controller/MyPageController.java
  src/main/java/life/inha/icemarket/domain/Chat.java
  src/main/java/life/inha/icemarket/domain/Post.java
  src/main/java/life/inha/icemarket/domain/Room.java
  src/main/java/life/inha/icemarket/domain/User.java
  src/main/java/life/inha/icemarket/domain/auth/User.java
  src/main/java/life/inha/icemarket/dto/MyPageDto.java
  src/main/java/life/inha/icemarket/respository/ChatRepository.java
  src/main/java/life/inha/icemarket/respository/RoomRepository.java
  src/main/java/life/inha/icemarket/respository/UserRepository.java
  src/main/java/life/inha/icemarket/service/MyPageService.java
  src/main/resources/application.properties
  src/test/java/life/inha/icemarket/controller/MyPageControllerTest.java
  src/test/java/life/inha/icemarket/controller/core/dummy.txt
  src/test/java/life/inha/icemarket/domain/auth/dummy.txt
  src/test/java/life/inha/icemarket/domain/core/dummy.txt
  src/test/java/life/inha/icemarket/domain/dummy.txt
  src/test/java/life/inha/icemarket/service/auth/dummy.txt
  src/test/java/life/inha/icemarket/service/core/dummy.txt
  src/test/java/life/inha/icemarket/service/dummy.txt
Labels: bug, enhancement

#16 [Feature/#14] 복지물품 대여 서비스 CRUD 구현
  db/init.sql
  src/main/java/life/inha/icemarket/config/SecurityConfig.java
  src/main/java/life/inha/icemarket/controller/ChatController.java
  src/main/java/life/inha/icemarket/controller/ItemController.java
  src/main/java/life/inha/icemarket/controller/ItemHistoryController.java
  src/main/java/life/inha/icemarket/domain/Chat.java
  src/main/java/life/inha/icemarket/domain/Item.java
  src/main/java/life/inha/icemarket/domain/ItemHistory.java
  src/main/java/life/inha/icemarket/domain/Post.java
  src/main/java/life/inha/icemarket/domain/Room.java
  src/main/java/life/inha/icemarket/domain/User.java
  src/main/java/life/inha/icemarket/dto/ItemHistorySaveRequestDto.java
  src/main/java/life/inha/icemarket/dto/ItemSaveRequestDto.java
  src/main/java/life/inha/icemarket/dto/MyPageDto.java
  src/main/java/life/inha/icemarket/respository/ItemHistoryRepository.java
  src/main/java/life/inha/icemarket/respository/ItemRepository.java
  src/main/java/life/inha/icemarket/service/ItemHistoryService.java
  src/main/java/life/inha/icemarket/service/ItemService.java
Labels: enhancement

#19 [Hotfix/#16] Fix incomplete method name and lint code
  src/main/java/life/inha/icemarket/config/SecurityConfig.java
  src/main/java/life/inha/icemarket/controller/ChatController.java
  src/main/java/life/inha/icemarket/controller/ItemController.java
  src/main/java/life/inha/icemarket/controller/ItemHistoryController.java
  src/main/java/life/inha/icemarket/domain/Item.java
  src/main/java/life/inha/icemarket/domain/ItemHistory.java
  src/main/java/life/inha/icemarket/domain/User.java
  src/main/java/life/inha/icemarket/dto/ItemHistorySaveRequestDto.java
  src/main/java/life/inha/icemarket/dto/ItemSaveRequestDto.java
  src/main/java/life/inha/icemarket/dto/MyPageDto.java
  src/main/java/life/inha/icemarket/respository/ItemHistoryRepository.java
  src/main/java/life/inha/icemarket/respository/ItemRepository.java
  src/main/java/life/inha/icemarket/service/ItemHistoryService.java
  src/main/java/life/inha/icemarket/service/ItemService.java
Labels: bug

#21 [Feature/#20] Swgger API 문서화
  build.gradle
  src/main/java/life/inha/icemarket/config/swagger/ApiDocumentResponse.java
  src/main/java/life/inha/icemarket/config/swagger/SwaggerConfig.java
  src/main/java/life/inha/icemarket/controller/ChatController.java
  src/main/java/life/inha/icemarket/controller/ItemController.java
  src/main/java/life/inha/icemarket/controller/ItemHistoryController.java
  src/main/java/life/inha/icemarket/controller/MyPageController.java
  src/test/java/life/inha/icemarket/controller/MyPageControllerTest.java
Labels: documentation, enhancement
